# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Kyle McGraw
# Description of the Site
description: BCI Data Scientist, AI Engineer
# URL of Image of the Site
site-image: /assets/images/bci7.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/bci7.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kmcgrawca@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: kyle-a-mcgraw
github_username:  kylmcgr
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Kyle McGraw
# URL for the Image of the Author
author-image: /assets/images/IMG_5505.HEIC
# 60 Words About the Author
author-about: |
  Hi! I'm <strong>Kyle McGraw</strong>. I'm a data scientist and AI engineer based in New York, NY.<br><br>
  I am a quick learner that is always looking to pick up new skills and use these skills to solve complex problems. I am passionate about using computational techniques to solve real-world problems and have a particular interest in brain-computer interfaces (BCI).<br><br>
  I was most recently a BCI data scientist at<a href="https://ae.studio">AE Studio</a>. I wore many hats while working at AE including: software engineer, contributing to our open-source<a href="https://agencyenterprise.github.io/neurotechdevkit/">Neurotech Development Kit (NDK)</a>software; BCI consultant, validating and prioritizing features for <a href="https://nextsense.io">NextSense</a>'s in-ear EEG earbuds; machine learning engineer, developing surrogate models to speed up focused ultrasound steady-state simulations for our NDK software and a basketball highlight play detection model for <a href="https://www.athlete.ai">Athlete.AI</a>'s app; and AI engineer, creating a bot that coaches kids through mistakes on their math tests and an LLM quality control and content generation system for reading comprehension articles and quizzes for <a href="https://alpha.school">Alpha School</a>.<br><br>
  Some of my other previous work includes developing<a href="https://github.com/kylmcgr/Surgical-Risk-Calculator-SURF">machine learning models for surgical risk prediction</a> (two papers in the works!), writing a <a href="https://github.com/kylmcgr/GPU-3D-Beamformer">GPU-based beamformer for 3D, real-time ultrasound imaging</a>, and working with <a href="https://sumnernorman.com">Sumner Norman</a> (currently doing very cool work at <a href="https://forestneurotech.org">Forest Neurotech</a>) to develop a <a href="https://github.com/kylmcgr/BCI-Project">functional ultrasound-based brain-computer interface</a>.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/kylmcgr

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
